version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Etc/UTC"
    groups:
      microsoft-aspnetcore:
        patterns:
          - "Microsoft.AspNetCore.*"
      xunit:
        patterns:
          - "xunit*"
      nats:
        patterns:
          - "NATS.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Etc/UTC"
